name: Sandbox release

on:
  push:
    branches: [ feat/log-me ]

jobs:
  build:
    runs-on: windows-2019
    outputs:
      Versions: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: 5.x

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        id: gitversion # step id used as reference for output values

      - name: Display GitVersion outputs
        run: |
          echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
          echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"

      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: '5.x'

      - name: Restore Nuget packages
        run: nuget restore LogMe.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Project
        run: msbuild .\LogMe.sln /p:Configuration=Release

      - name: Build Nuget package
        run: nuget pack .\src\BuildCell.LogMe\BuildCell.LogMe.csproj -Properties Configuration=Release

      - name: Upload NuGet Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'artifact'
          path: src/BuildCell.LogMe/
  
  release:
    runs-on: windows-2019
    needs: build
    
    steps:
      - name: Create release in github
        if: needs.build.outputs.CommitsSinceVersionSource > 0
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.Version }}
          name: Release ${{ needs.build.outputs.Version }}
          artifacts: "artifact/*"