name: Sandbox release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    outputs:
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: 5.x

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        id: gitversion # step id used as reference for output values

      - name: Display GitVersion outputs
        run: |
          echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
          echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"

      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: '5.x'

      - name: Restore Nuget packages
        run: nuget restore LogMe.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Project
        run: msbuild .\LogMe.sln /p:Configuration=Release

      - name: Build Nuget package
        run: nuget pack .\src\BuildCell.LogMe\BuildCell.LogMe.csproj -Version ${{ steps.gitversion.outputs.SemVer }} -Properties Configuration=Release

      - name: Upload NuGet Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nuget-Package
          path: BuildCell.LogMe.${{ steps.gitversion.outputs.SemVer }}.nupkg 
  
  release:
    runs-on: windows-2019
    needs: build
    
    steps:
      - name: Download nuget package artifact
        uses: actions/download-artifact@v4
        with:
          name: Nuget-Package
          
      - name: Debug - List files
        run: Get-ChildItem -Recurse

      - name: Create release in github
        if: needs.build.outputs.CommitsSinceVersionSource > 0
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.Version }}
          name: ${{ needs.build.outputs.Version }}
          artifacts: "BuildCell.LogMe.${{ needs.build.outputs.Version }}.nupkg"
